vich_uploader:
    db_driver: orm

    mappings:
       credits_image:
           uri_prefix: /images/credits
           upload_destination: '%kernel.project_dir%/public/images/credits'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
