vich_uploader:
    db_driver: orm

    mappings:
       credits_image:
           uri_prefix: /img/credits
           upload_destination: '%kernel.project_dir%/public/img/credits'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
