<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGmvWS0R\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGmvWS0R/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGmvWS0R.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGmvWS0R\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGmvWS0R\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GmvWS0R',
    'container.build_id' => '2051bfe8',
    'container.build_time' => 1585315889,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGmvWS0R');
